"""Stopword classification for concept extraction.

Stopword lists target tokens that appear in code or comments with extremely
high frequency and contribute no semantic signal to concept ranking. They are
NOT removed from the concept graph — they continue to receive REFERENCES and
IS_NAMED_IN edges (so queries can still find them as nodes). They are excluded
from CO_OCCURS_WITH (by the extractor) and from centrality computation (by the
retrieval layer). Conservative on English (avoid losing meaningful nouns/verbs);
aggressive on language keywords (always syntactic).

``classify()`` returns a ``StopwordClass``; callers decide how to apply it.
English and code stop-lists are global; per-language lists add keyword noise
from each grammar.
"""

from __future__ import annotations

import logging
import threading
from collections.abc import Iterable
from enum import Enum

log = logging.getLogger(__name__)


class StopwordClass(str, Enum):
    NOT_STOPWORD = 'not_stopword'
    ENGLISH = 'english'
    CODE = 'code'
    LANGUAGE = 'language'


ENGLISH_STOPWORDS: frozenset[str] = frozenset(
    {
        # Articles + conjunctions + auxiliaries.
        'a',
        'actually',
        'after',
        'again',
        'against',
        'all',
        'also',
        'always',
        'although',
        'among',
        'an',
        'and',
        'another',
        'any',
        'anyhow',
        'anyway',
        'are',
        'around',
        'as',
        'at',
        'back',
        'basically',
        'be',
        'because',
        'been',
        'before',
        'behind',
        'below',
        'beneath',
        'beside',
        'between',
        'beyond',
        'both',
        'but',
        'by',
        'can',
        'cannot',
        'could',
        'did',
        'do',
        'does',
        'done',
        'doing',
        'down',
        'during',
        'each',
        'either',
        'essentially',
        'even',
        'every',
        'few',
        'for',
        'from',
        'furthermore',
        'had',
        'has',
        'have',
        'having',
        'he',
        'hence',
        'her',
        'here',
        'him',
        'his',
        'how',
        'however',
        'in',
        'indeed',
        'instead',
        'into',
        'is',
        'it',
        'its',
        'just',
        'less',
        'like',
        'looks',
        'many',
        'maybe',
        'might',
        'more',
        'moreover',
        'most',
        'much',
        'must',
        'never',
        'no',
        'none',
        'nor',
        'not',
        'now',
        'of',
        'off',
        'often',
        'on',
        'once',
        'one',
        'only',
        'onto',
        'or',
        'other',
        'otherwise',
        'our',
        'out',
        'over',
        'perhaps',
        'quite',
        'rather',
        'really',
        'said',
        'she',
        'should',
        'since',
        'so',
        'some',
        'sometimes',
        'somewhat',
        'somewhere',
        'somehow',
        'still',
        'such',
        'than',
        'that',
        'the',
        'their',
        'them',
        'then',
        'there',
        'therefore',
        'these',
        'they',
        'this',
        'those',
        'though',
        'three',
        'through',
        'throughout',
        'thus',
        'to',
        'today',
        'too',
        'two',
        'under',
        'until',
        'unchanged',
        'up',
        'upon',
        'us',
        'usually',
        'very',
        'via',
        'was',
        'we',
        'well',
        'were',
        'what',
        'when',
        'where',
        'which',
        'while',
        'who',
        'whose',
        'why',
        'will',
        'with',
        'within',
        'without',
        'would',
        'you',
        'your',
    },
)

CODE_STOPWORDS: frozenset[str] = frozenset(
    {
        'add',
        'arg',
        'args',
        'callable',
        'called',
        'contains',
        'context',
        'count',
        'current',
        'debug',
        'default',
        'empty',
        'err',
        'error',
        'ex',
        'exception',
        'factory',
        'false',
        'first',
        'get',
        'handler',
        'helper',
        'index',
        'info',
        'init',
        'instance',
        'item',
        'kwargs',
        'label',
        'last',
        'length',
        'log',
        'logger',
        'manager',
        'name',
        'next',
        'nil',
        'none',
        'null',
        'obj',
        'options',
        'param',
        'prev',
        'provider',
        'remove',
        'result',
        'run',
        'set',
        'size',
        'temp',
        'thread',
        'true',
        'value',
        'var',
        'win',
        'window',
    },
)

_CSHARP_KEYWORDS: frozenset[str] = frozenset(
    {
        'abstract',
        'as',
        'async',
        'await',
        'base',
        'bool',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'checked',
        'class',
        'const',
        'continue',
        'decimal',
        'default',
        'delegate',
        'do',
        'double',
        'else',
        'enum',
        'event',
        'explicit',
        'extern',
        'file',
        'finally',
        'fixed',
        'float',
        'for',
        'foreach',
        'global',
        'goto',
        'if',
        'implicit',
        'in',
        'init',
        'int',
        'interface',
        'internal',
        'is',
        'lock',
        'long',
        'namespace',
        'new',
        'object',
        'operator',
        'out',
        'override',
        'params',
        'partial',
        'private',
        'protected',
        'public',
        'readonly',
        'record',
        'ref',
        'required',
        'return',
        'scoped',
        'sealed',
        'short',
        'sizeof',
        'static',
        'string',
        'struct',
        'switch',
        'this',
        'throw',
        'try',
        'typeof',
        'uint',
        'ulong',
        'unchecked',
        'unsafe',
        'ushort',
        'using',
        'var',
        'virtual',
        'void',
        'volatile',
        'when',
        'where',
        'while',
        'with',
        'yield',
    },
)

_CSHARP_XMLDOC_ELEMENTS: frozenset[str] = frozenset(
    {
        'b',
        'br',
        'c',
        'code',
        'cref',
        'description',
        'example',
        'exception',
        'i',
        'inheritdoc',
        'item',
        'list',
        'listheader',
        'note',
        'para',
        'param',
        'paramref',
        'remarks',
        'returns',
        'see',
        'seealso',
        'summary',
        'term',
        'typeparam',
        'typeparamref',
        'value',
    },
)

LANGUAGE_STOPWORDS: dict[str, frozenset[str]] = {
    'csharp': _CSHARP_KEYWORDS | _CSHARP_XMLDOC_ELEMENTS,
    'python': frozenset(
        {
            'and',
            'as',
            'assert',
            'async',
            'await',
            'break',
            'class',
            'cls',
            'continue',
            'def',
            'del',
            'elif',
            'else',
            'except',
            'false',
            'finally',
            'for',
            'from',
            'global',
            'if',
            'import',
            'in',
            'is',
            'lambda',
            'nonlocal',
            'none',
            'not',
            'or',
            'pass',
            'raise',
            'return',
            'self',
            'true',
            'try',
            'while',
            'with',
            'yield',
        },
    ),
    'typescript': frozenset(
        {
            'any',
            'as',
            'asserts',
            'async',
            'await',
            'boolean',
            'break',
            'case',
            'catch',
            'class',
            'const',
            'continue',
            'default',
            'do',
            'else',
            'export',
            'extends',
            'false',
            'finally',
            'for',
            'from',
            'function',
            'if',
            'implements',
            'import',
            'infer',
            'instanceof',
            'interface',
            'is',
            'keyof',
            'let',
            'never',
            'new',
            'null',
            'number',
            'object',
            'of',
            'private',
            'protected',
            'public',
            'readonly',
            'return',
            'static',
            'string',
            'super',
            'switch',
            'this',
            'throw',
            'true',
            'try',
            'type',
            'typeof',
            'undefined',
            'unknown',
            'var',
            'void',
            'while',
            'yield',
        },
    ),
    'javascript': frozenset(
        {
            'const',
            'interface',
            'let',
            'type',
            'var',
        },
    ),
}

_lock = threading.Lock()
_english_extensions: set[str] = set()
_code_extensions: set[str] = set()
_language_extensions: dict[str, set[str]] = {}


def classify(token: str, *, language: str | None = None) -> StopwordClass:
    """Classify *token* for centrality penalty — never implies hard drop."""
    normalized = token.lower()
    with _lock:
        if normalized in ENGLISH_STOPWORDS or normalized in _english_extensions:
            return StopwordClass.ENGLISH
        if normalized in CODE_STOPWORDS or normalized in _code_extensions:
            return StopwordClass.CODE
        if language is not None:
            lang_key = language.lower()
            lang_set = LANGUAGE_STOPWORDS.get(lang_key, frozenset())
            lang_ext = _language_extensions.get(lang_key, set())
            if normalized in lang_set or normalized in lang_ext:
                return StopwordClass.LANGUAGE
    return StopwordClass.NOT_STOPWORD


def is_stopword(token: str, *, language: str | None = None) -> bool:
    """Return True when *token* matches any stopword category."""
    return classify(token, language=language) != StopwordClass.NOT_STOPWORD


def extend_stopwords(
    *,
    english: Iterable[str] = (),
    code: Iterable[str] = (),
    language: dict[str, Iterable[str]] | None = None,
) -> None:
    """Add project- or test-specific stopwords in a thread-safe way."""
    with _lock:
        _english_extensions.update(word.lower() for word in english)
        _code_extensions.update(word.lower() for word in code)
        if language:
            for lang, words in language.items():
                lang_key = lang.lower()
                bucket = _language_extensions.setdefault(lang_key, set())
                bucket.update(word.lower() for word in words)
